### ISSUE TITLE
step fails when variable names are long

### ISSUE THREAD

**Issue by smyth7** [runehaubo/lmerTestR#13]
Hi,

I find that step.lmerModLmerTest fails at some point when there are variables with 'long' names and their interactions. Renaming variables to one character and repeating works fine. In my example I had 10 variables plus their interactions.

Paul

**Comment by runehaubo** [comment]
Thanks for the report. The restriction is due to `deparse` which has a `500L` characters limit. On the top of my head I don't see a way to circumvent this, but pull requests are always welcome.

**Comment by runehaubo** [comment]
I think we have this fixed now using af safer `deparse`ing but without a reproducible example I'm not sure.
