### ISSUE TITLE
Error in rand(fm1) : could not find function "rand"

### ISSUE THREAD

**Issue by nmjakobsen** [runehaubo/lmerTestR#14]
Using lmerTest version 3.0-1 with R version 3.5.1, I encounter the above error when running the following code: 

```
library(lmerTest)
fm1 <- lmer(Reaction ~ Days + (Days|Subject), sleepstudy)
ranova(fm1) # Works
rand(fm1) # Doesn't work
```

According to the `ranova` help page, `rand` is an alias for `ranova`, so as far as I can see, the last line of code should generate the same output as the previous line.

Kind regards,
Nina

**Comment by runehaubo** [comment]
Indeed you should get the same results for `rand` as for `ranova` (and you would if you used `lmerTest:::rand(fm1)`). Unfortunately a simple export statement was missing and embarrassingly `rand` was not explicitly tested :-(. Installing version `3.0-1.9003` of `lmerTest` (`devtools::install_github("runehaubo/lmerTestR")`) which I am committing shortly should solve this issue. 

Thank you for raising this issue.

Cheers
Rune
