### ISSUE TITLE
feature: progress bar for lmer() computing

### ISSUE THREAD

**Issue by b1azk0** [runehaubo/lmerTestR#15]
Hello,
would it be possible to add a simple progress bar for the model computation?
1/100 steps or something like this?
I often find myself waiting for models couple of hours and this would help a lot in planning the CPU workload :)

Thanks #

**Comment by runehaubo** [comment]
The model fitting is done by `lme4::lmer` and a progress bar should be (and has been) discussed in the context of the lme4 package, so I'm going to close this issue here.
