### ISSUE TITLE
Unnecessary message

### ISSUE THREAD

**Issue by meierluk** [runehaubo/lmerTestR#19]
The following R-code produces an unnecessary message due to a centered continuous predictor. 

```
data("Orthodont", package = "nlme")

library(lmerTest)

Orthodont[,"age"] <- Orthodont[,"age"] - 11 ## center the time covariate
  
fit <- lmer(distance ~ Sex * age + (age | Subject), data = Orthodont)
anova(fit)
```
```
Missing cells for: age, SexMale:age, SexFemale:age.  
Interpret type III hypotheses with care.
```

**Comment by runehaubo** [comment]
Thanks for mentioning - I'll take a look.

/Rune

**Comment by nefears** [comment]
Was the reason for this error ever determined?

**Comment by TheDom42** [comment]
I ran into the same issue the other day. Is this an actually unnecessary/incorrect warning or is this something one should worry about because it points to an issue in calculation?
Put differently: can I ignore it as long as I know that my data does not actually contain any `NA`s?

**Comment by meierluk** [comment]
I think the calculations are fine.

**Comment by meierluk** [comment]
@runehaubo  : Did you ever find out something regarding this issue?

**Comment by runehaubo** [comment]
@meierluk thanks for your persistency - this is now fixed.

Cheers
Rune

**Comment by meierluk** [comment]
@runehaubo Nice, thanks a lot
