### ISSUE TITLE
Question about lmerTest

### ISSUE THREAD

**Issue by kevinmchu** [runehaubo/lmerTestR#28]
I built a linear mixed effects model and would like to test the statistical significance of the fixed factor coefficients using the lmerTest package. However, I am not entirely sure how to test for significance, so I have a couple of questions.

1) Can I test for significance by passing the mixed effects object through the anova method?
2) Do I need to run the step method if I am testing for coefficient significance?

**Comment by runehaubo** [comment]
You can use anova() summary() drop1() and ranova() for random effects -
there is no need for step in this case.

Cheers
Rune

man. 9. sep. 2019 kl. 18.51 skrev kevinmchu <notifications@github.com>:

**Comment by kevinmchu** [comment]
Thank you for your prompt reply. Do I need all those methods to test for statistical significance of fixed effects coefficients? Or can I pass the lmm object directly to the anova function?

**Comment by runehaubo** [comment]
You may only need the anova function depending on your situation - try out
the functions and see if you get what you want. Further questions long
these lines should be sent to the mixed-models mailing list
https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models

Cheers
Rune
