### ISSUE TITLE
Number of digits from the summary function

### ISSUE THREAD

**Issue by hknih** [runehaubo/lmerTestR#36]
I am relatively new with R and using the lmerTest package for a similar analysis that is presented in the package instructions:

fm <- lmer(Informed.liking ~ Gender + Information + (1 | Consumer),  data = data)
summary(fm)

However, the summary function prints out t and p values with 2 digits only. How can the number of digits be adjusted?

Thank you!

**Comment by runehaubo** [comment]
This is not particular to lmerTest, but

print(summary(fm), digits=<some-number>)

gives you some control.

Alternatively,

coef(summary(fm))

if you need to compute on the estimates.

Cheers
Rune

**Comment by hknih** [comment]
Thank you so much for the prompt response! print(summary(fm), digits = 3) did not change the number of digits with t and p values even though this is what I also originally assumed would have worked here, but with coef(summary(fm)) I get larger number of digits so this solved my problem, thank you!
